name: Build
on:
  push:
  schedule:
    - cron: 0 */6 * * *
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: ubuntu:groovy
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies and tools
        run: |
          apt-get update
          apt-get install -y wget git meson python3 python3-pip python3-setuptools python3-wheel ninja-build gcc pkg-config m4 libarchive-tools libarchive-dev libssl-dev curl html-xml-utils nodejs
          git clone https://gitlab.archlinux.org/pacman/pacman.git --depth=1 --branch=v5.2.2 2>&1
          cd pacman
          meson setup builddir
          meson install -C builddir
      - name: Create repo
        run: ./build.sh
      - name: Remove symlinks
        run: |
          rm repo/plasma-mobile/plasma-mobile.db repo/plasma-mobile/plasma-mobile.files
          cp repo/plasma-mobile/plasma-mobile.db.tar.xz repo/plasma-mobile/plasma-mobile.db
          cp repo/plasma-mobile/plasma-mobile.files.tar.xz repo/plasma-mobile/plasma-mobile.files
          rm repo/lomiri/lomiri.db repo/lomiri/lomiri.files
          cp repo/lomiri/lomiri.db.tar.xz repo/lomiri/lomiri.db
          cp repo/lomiri/lomiri.files.tar.xz repo/lomiri/lomiri.files
          rm repo/phosh/phosh.db repo/phosh/phosh.files
          cp repo/phosh/phosh.db.tar.xz repo/phosh/phosh.db
          cp repo/phosh/phosh.files.tar.xz repo/phosh/phosh.files
      - name: Upload repo
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: packages
          FOLDER: repo
          SKIP_EMPTY_COMMITS: true
          SQUASH_HISTORY: true
          MESSAGE: "Package updates"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
